version: "3.9"

services:

  backend:
    build: ./backend
    container_name: mail_jira_backend
    ports:
      - "9090:8000"
    volumes:
      - ./backend:/app
      - ./frontend:/frontend
    depends_on:
      - mongo
    environment:
      - TZ=Asia/Kolkata

  mongo:
    image: mongo:6
    container_name: mail_jira_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - TZ=Asia/Kolkata

volumes:
  mongo_data: